# Generated by Django 6.1.1 on 2026-09-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='people/')),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Door', max_length=80)),
                ('camera_number', models.PositiveIntegerField(unique=True)),
                ('points', models.JSONField(default=list)),
                ('dwell_seconds', models.PositiveIntegerField(default=60)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_number', models.PositiveIntegerField()),
                ('track_id', models.IntegerField()),
                ('snapshot', models.ImageField(upload_to='alarms/')),
                ('face_crop', models.ImageField(blank=True, upload_to='alarms/faces/')),
                ('face_embedding', models.BinaryField(blank=True, null=True)),
                ('matched_name', models.CharField(default='Unknown', max_length=120)),
                ('score', models.FloatField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
