# Generated by Django 5.2.13 on 2026-10-04 06:48

import camera.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DEFAULT_USER_FEATURES = ("live", "alarms", "recognition", "search")


def seed_accounts(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("camera", "UserProfile")
    FeatureGrant = apps.get_model("camera", "FeatureGrant")
    from django.contrib.auth.hashers import make_password

    admin, _created = User.objects.get_or_create(
        username="admin",
        defaults={
            "password": make_password("Admin1234"),
            "is_staff": True,
            "is_superuser": False,
            "is_active": True,
        },
    )
    UserProfile.objects.get_or_create(user=admin)
    operator, _created = User.objects.get_or_create(
        username="user",
        defaults={
            "password": make_password("User1234"),
            "is_staff": False,
            "is_superuser": False,
            "is_active": True,
        },
    )
    UserProfile.objects.get_or_create(user=operator)
    for code in DEFAULT_USER_FEATURES:
        FeatureGrant.objects.get_or_create(user=operator, feature=code)


def remove_seed_accounts(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=["admin", "user"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_alarm_facecapture_created_at_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=camera.models.avatar_upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'feature'), name='uniq_user_feature')],
            },
        ),
        migrations.RunPython(seed_accounts, remove_seed_accounts),
    ]
